import { PortfolioData } from '@/types/portfolio';

export interface CreateRepoParams {
  name: string;
  isPrivate: boolean;
  portfolio: PortfolioData;
  token?: string;
  githubUsername?: string;
}

export function cleanGithubUsername(input?: string): string {
  if (!input) return '';
  let cleaned = input.trim();
  cleaned = cleaned.replace(/^https?:\/\/(www\.)?github\.com\//i, '');
  cleaned = cleaned.replace(/\/.*$/, '');
  cleaned = cleaned.replace(/^@/, '');
  return cleaned;
}

export function formatGithubRepoUrl(owner: string, repoSlug: string): string {
  const cleanOwner = cleanGithubUsername(owner) || 'user';
  const cleanRepo = repoSlug.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  return `https://github.com/${cleanOwner}/${cleanRepo}`;
}

export async function createGithubRepository({ name, isPrivate, portfolio, token, githubUsername }: CreateRepoParams) {
  const cleanOwner = cleanGithubUsername(githubUsername) || 'user';

  let cleanSlug = name.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  if (!cleanSlug.endsWith('-portfolio')) {
    cleanSlug = `${cleanSlug}-portfolio`;
  }
  // Ensure no duplicate -portfolio-portfolio
  cleanSlug = cleanSlug.replace(/(-portfolio)+$/g, '-portfolio');

  const fallbackRepoUrl = formatGithubRepoUrl(cleanOwner, cleanSlug);

  // Strict check for GitHub Personal Access Token
  if (!token || token.trim().length < 5 || token.includes('placeholder')) {
    return {
      success: false,
      isTokenRequired: true,
      error: 'GitHub Personal Access Token is required to create a repository on your GitHub account. Please paste your GitHub token below.',
      repoUrl: fallbackRepoUrl,
      cloneUrl: `${fallbackRepoUrl}.git`,
      fullName: `${cleanOwner}/${cleanSlug}`,
    };
  }

  try {
    // 1. Create Repository on User's GitHub Account
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token.trim()}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Portify-AI-App',
      },
      body: JSON.stringify({
        name: cleanSlug,
        private: isPrivate,
        description: `Professional Portfolio for ${portfolio.personal.name} generated by Portify AI.`,
        auto_init: true,
      }),
    });

    const repoData = await createRes.json();

    if (!createRes.ok && createRes.status !== 422) {
      return {
        success: false,
        isTokenRequired: true,
        error: repoData.message || 'GitHub authentication failed. Please verify your token has "repo" scope.',
      };
    }

    const actualOwner = cleanGithubUsername(repoData.owner?.login || cleanOwner);
    const repoFullName = repoData.full_name || `${actualOwner}/${cleanSlug}`;
    const repoHtmlUrl = formatGithubRepoUrl(actualOwner, cleanSlug);

    // 2. Commit README.md and portfolio.json into user's GitHub repo
    const readmeContent = generateReadmeContent(portfolio, `https://${cleanSlug}.vercel.app`, repoHtmlUrl);
    await commitFileToRepo({
      token: token.trim(),
      owner: actualOwner,
      repo: cleanSlug,
      path: 'README.md',
      content: readmeContent,
      message: 'docs: add professional README portfolio documentation',
    });

    const portfolioJsonContent = JSON.stringify(portfolio, null, 2);
    await commitFileToRepo({
      token: token.trim(),
      owner: actualOwner,
      repo: cleanSlug,
      path: 'portfolio.json',
      content: portfolioJsonContent,
      message: 'feat: add standalone portfolio dataset',
    });

    const packageJsonContent = JSON.stringify(
      {
        name: cleanSlug,
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
        },
        dependencies: {
          next: '^14.2.0',
          react: '^18.3.0',
          'react-dom': '^18.3.0',
          'lucide-react': '^0.378.0',
          tailwindcss: '^3.4.0',
        },
      },
      null,
      2
    );

    await commitFileToRepo({
      token: token.trim(),
      owner: actualOwner,
      repo: cleanSlug,
      path: 'package.json',
      content: packageJsonContent,
      message: 'chore: initialize Next.js package configuration',
    });

    return {
      success: true,
      repoUrl: repoHtmlUrl,
      cloneUrl: `${repoHtmlUrl}.git`,
      fullName: repoFullName,
    };
  } catch (err: any) {
    return {
      success: false,
      error: `GitHub API execution error: ${err.message}`,
    };
  }
}

async function commitFileToRepo({
  token,
  owner,
  repo,
  path,
  content,
  message,
}: {
  token: string;
  owner: string;
  repo: string;
  path: string;
  content: string;
  message: string;
}) {
  try {
    const base64Content = typeof window !== 'undefined' ? btoa(unescape(encodeURIComponent(content))) : Buffer.from(content).toString('base64');

    let sha: string | undefined;
    const getRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'Portify-AI-App',
      },
    });
    if (getRes.ok) {
      const getJson = await getRes.json();
      sha = getJson.sha;
    }

    await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Portify-AI-App',
      },
      body: JSON.stringify({
        message,
        content: base64Content,
        sha,
      }),
    });
  } catch (err) {
    console.error(`Failed to commit ${path} to GitHub:`, err);
  }
}

export function generateReadmeContent(portfolio: PortfolioData, liveUrl: string, repoUrl: string): string {
  return `# ${portfolio.personal.name} — Portfolio Website

> Generated automatically by **Portify AI**

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new)
[![Portify AI](https://img.shields.io/badge/Built%20With-Portify%20AI-0c8ee9)](https://portfolio-maker-topaz.vercel.app)

## 🚀 Live Demo
**URL**: [${liveUrl}](${liveUrl})

## 👤 About Developer
- **Name**: ${portfolio.personal.name}
- **Role**: ${portfolio.personal.title}
- **Location**: ${portfolio.personal.location}
- **Email**: ${portfolio.personal.email}

## 🛠️ Technology Stack
- **Framework**: Next.js 14 (App Router)
- **Styling**: Tailwind CSS
- **Icons**: Lucide Icons
- **Language**: TypeScript

## 📦 Local Setup & Execution
\`\`\`bash
# 1. Clone repository
git clone ${repoUrl}.git

# 2. Install dependencies
npm install

# 3. Run development server
npm run dev
\`\`\`

---
*Created using [Portify AI](https://portfolio-maker-topaz.vercel.app)*
`;
}
